# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 798bafde24d8cfdea8ac0d8790cb582fbd8dbf9cd39549d93b0c984fc8a1764259f0408e93955cef893b98c0137c77f052ecb98500da19e8a51ed8f9605bde76

test:
  secret_key_base: cad8ab7281051962759ed36660ede69c9201f7cec7f2f1f64d3d7e59cbc88b903954754cb0cdf35fc942f94577cdb9c0b02f6e23c1556a58ae4f676cd04dd365

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
